### ISSUE TITLE
no "&" nesting selector in plain css

### ISSUE THREAD

**Issue by SpiritAxolotl** [cpsdqs/prechoster#14]
<https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector>

example use:
```css
pre {
  border-radius: 0;
  box-sizing: border-box;
  padding: 0.5rem;
  margin: 1.25rem 0 0;
  line-height: 1.5;
  overflow-x: auto;
  color-scheme: dark;
  background: rgb(13, 17, 23);
  color: rgb(230, 237, 243);
  width: 100%;
  font-size: x-small;
  overscroll-behavior: none;
  &:first-of-type {
    border-top-left-radius: 0.25rem;
    border-right: 2px solid rgb(57, 57, 57);
  }
  &:last-of-type {
    border-top-right-radius: 0.25rem;
    border-left: 2px solid rgb(57, 57, 57);
  }
}
```

the output: 
<img width="538" alt="Screenshot 2024-05-09 at 4 41 51 PM" src="https://github.com/cpsdqs/prechoster/assets/83354374/b6e3ff44-b83c-4192-a60e-90aa2ae46022">

just would be cool to have :)
